webcamp-donut/nagano_cake

app/assets/javascripts/order_products.coffee, app/assets/javascripts/orders.coffee, app/assets/stylesheets/order_products.scss, app/assets/stylesheets/orders.scss, app/controllers/order_products_controller.rb, app/controllers/orders_controller.rb, app/helpers/order_products_helper.rb, app/helpers/orders_helper.rb, app/models/order.rb, app/models/order_product.rb, app/views/order_products/update.html.erb, app/views/orders/index.html.erb, app/views/orders/show.html.erb, app/views/orders/top.html.erb, app/views/orders/update.html.erb, db/migrate/20200916112403_create_orders.rb, db/migrate/20200916112629_create_order_products.rb, db/schema.rb, test/controllers/order_products_controller_test.rb, test/controllers/orders_controller_test.rb, test/fixtures/order_products.yml, test/fixtures/orders.yml, test/models/order_product_test.rb, test/models/order_test.rb
モデル＆コントローラ作成
Order
OrderProduct
=> add order & order_products_model

app/models/genre.rb, app/models/product.rb, config/initializers/devise.rb, config/routes.rb, db/migrate/20200916112420_create_products.rb, db/migrate/20200916112539_create_genres.rb, db/migrate/20200916113500_add_last_name_to_members.rb, db/migrate/20200916114109_add_first_name.rb, db/migrate/20200916114643_add_first_name_to_members.rb, db/schema.rb, test/fixtures/genres.yml, test/fixtures/products.yml, test/models/genre_test.rb, test/models/product_test.rb
=> add model table column

app/assets/javascripts/application.js, app/assets/javascripts/shipping_addresses.coffee, app/assets/stylesheets/shipping_addresses.scss, app/controllers/shipping_addresses_controller.rb, app/helpers/shipping_addresses_helper.rb, app/views/shipping_addresses/edit.html.erb, app/views/shipping_addresses/index.html.erb, app/views/shipping_addresses/new.html.erb, app/views/shipping_addresses/update.html.erb, config/application.rb, config/environments/development.rb, db/seeds.rb, test/controllers/shipping_addresses_controller_test.rb
追加機能
配送先一覧を表示する。
新しい配送先を登録する。
配送先新規登録
配送先編集画面を表示する。
配送先を更新する。
配送先を削除する。
フロント部分は未完成です。
=> shipping_address:back_part

app/assets/stylesheets/application.scss, app/views/members/sessions/new.html.erb, app/views/members/show.html.erb, app/views/products/index.html.erb, db/schema.rb
=> mypage_front

app/assets/stylesheets/homes.scss, app/assets/stylesheets/orders.scss, app/views/orders/confirmation.html.erb, app/views/orders/index.html.erb, app/views/orders/new.html.erb, app/views/orders/show.html.erb, app/views/orders/thank.html.erb
会員の注文画面のフロント部分になります。
・注文情報入力
・注文確認
・購入完了
・注文履歴一覧
・注文履歴詳細
=> Member order front

app/views/shipping_addresses/edit.html.erb, app/views/shipping_addresses/index.html.erb, app/views/shipping_addresses/update.html.erb
=> add_member_shipping_address_view

app/assets/stylesheets/application.scss, app/views/members/edit.html.erb
=> mypage_edit

app/assets/stylesheets/application.scss, app/views/members/confirmation.html.erb
=> withdrawel_confirmation

app/views/admins/orders/top.html.erb
=> admins_top

app/assets/javascripts/admins/order_products.coffee, app/assets/stylesheets/admins/order_products.scss, app/controllers/admins/order_products_controller.rb, app/controllers/admins/orders_controller.rb, app/controllers/admins/products_controller.rb, app/controllers/order_products_controller.rb, app/controllers/orders_controller.rb, app/helpers/admins/order_products_helper.rb, app/models/order.rb, app/models/order_product.rb, app/views/admins/orders/index.html.erb, app/views/admins/orders/show.html.erb, test/controllers/admins/order_products_controller_test.rb
管理者側の注文一覧画面
管理者側の注文詳細画面
ステータスの自動更新
を作成しました
=> first commit

app/views/admins/genres/_research.html.erb, app/views/admins/registrations/new.html.erb, app/views/products/show.html.erb
=> Member product detail view

app/assets/stylesheets/application.scss, app/controllers/products_controller.rb, app/views/kaminari/_first_page.html.erb, app/views/kaminari/_gap.html.erb, app/views/kaminari/_last_page.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/kaminari/_prev_page.html.erb, app/views/products/index.html.erb, config/initializers/kaminari_config.rb, db/seeds.rb
=> products_index

app/assets/javascripts/genres.coffee, app/assets/stylesheets/genres.scss, app/controllers/genres_controller.rb, app/controllers/members/sessions_controller.rb, app/controllers/products_controller.rb, app/helpers/genres_helper.rb, app/models/member.rb, app/views/admins/genres/_research.html.erb, app/views/genres/show.html.erb, app/views/homes/top.html.erb, app/views/members/sessions/new.html.erb, app/views/products/index.html.erb, config/routes.rb, test/controllers/genres_controller_test.rb
退会後ログインできなくする機能
ジャンル検索でジャンル別のviewに飛ぶ様追加
ジャンル別のviewページ作成
=> Withdrawal

app/assets/stylesheets/application.scss, app/views/admins/genres/_research.html.erb, app/views/layouts/application.html.erb
・ジャンル検索　・商品一覧　デザイン修正　・アプリの背景色変更
=> add_produtsindex_jenrereserch

app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb
=> add_footer

app/assets/stylesheets/application.scss, app/views/members/registrations/new.html.erb
商品一覧のデザイン、ジャンルのデザイン、フッターの修正、メンバーの新規登録画面のフロント
=> applicationcolor_addfooter_mamberregistration

app/controllers/admins/genres_controller.rb, app/controllers/admins/members_controller.rb, app/controllers/admins/order_products_controller.rb, app/controllers/admins/orders_controller.rb, app/controllers/admins/products_controller.rb, app/controllers/cart_items_controller.rb, app/controllers/order_products_controller.rb, app/controllers/orders_controller.rb, app/controllers/shipping_addresses_controller.rb
authenticate_member
authenticate_admin
=> authenticate

app/views/admins/orders/show.html.erb, app/views/admins/products/edit.html.erb, app/views/admins/products/new.html.erb, app/views/members/registrations/new.html.erb
管理者
商品編集、商品新規登録レイアウト修正
会員
サインアップ画面レイアウト修正
=> layout_update

app/models/member.rb, app/models/shipping_address.rb
=> modify_validate

app/controllers/orders_controller.rb, app/views/cart_items/index.html.erb, app/views/members/app.js, app/views/members/confirmation.html.erb, app/views/members/show.html.erb
・注文情報入力画面で新しいお届け先を選択時に、次の画面を進めない状態を修正。
・退会時に出てくるjsアラートを削除
=> modify_order_new

app/views/thanks_mailer/thanks_email.html.erb
=> change_mail_content

app/assets/javascripts/application.js, app/assets/stylesheets/application.scss
フッターにボタンが重ならないようにbodyにpadding-bottomを設定しました。
=> add_body_padding

app/controllers/searchs_controller.rb, app/mailers/thanks_mailer.rb, app/models/member.rb, app/views/members/app 2.js, app/views/searchs/search.html.erb, db/seeds.rb
=> add_member_research

app/assets/javascripts/application.js, app/controllers/members_controller.rb
画像プレビュー表示にturbolinks追加
管理者ログイン中のロゴにリンクを管理者トップへ変更
=> add_turbolinks
